# Generated by Django 2.2.10 on 2020-09-03 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('file', models.FileField(default='not', upload_to='files')),
                ('note', models.TextField(default='No Detail', verbose_name='Detail')),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'expense',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feetype_name', models.CharField(max_length=50)),
                ('feetype_note', models.TextField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'feetype',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('file', models.FileField(default='not', upload_to='files')),
                ('note', models.TextField(default='No Detail', verbose_name='Detail')),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'income',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Partially Paid', 'Partially Paid'), ('Fully Paid', 'Fully Paid')], max_length=25)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=10)),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Classes')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Admission')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'invoicedetail',
            },
        ),
        migrations.CreateModel(
            name='InvoiceAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('discount', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.FeeType')),
                ('invoicedetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.InvoiceDetail')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'invoiceamount',
            },
        ),
    ]
