# Generated by Django 2.2.10 on 2020-09-03 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Teacher'),
        ),
        migrations.AddField(
            model_name='classes',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Section'),
        ),
    ]
