# Generated by Django 2.2.10 on 2020-09-03 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=25)),
                ('father_name', models.CharField(max_length=25)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('fee_month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('monthly_tution_fee', models.IntegerField()),
                ('monthly_tution_fee_paid', models.IntegerField(default=0)),
                ('challan_number', models.CharField(max_length=10)),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Classes')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Section')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Admission')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'voucher',
            },
        ),
    ]
