# Generated by Django 2.2.10 on 2020-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='email_address',
            field=models.CharField(default='info@intelexcel.com', max_length=100),
        ),
    ]
