# Generated by Django 2.2.10 on 2020-09-03 23:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=50)),
                ('rate_per_hour', models.IntegerField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Schedual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.CharField(max_length=10)),
                ('time_out', models.CharField(max_length=10)),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'schedual',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('designation', models.CharField(max_length=70, verbose_name='Role')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=70)),
                ('religion', models.CharField(default='not mentioned', max_length=70)),
                ('Phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_join', models.DateField()),
                ('status', models.IntegerField(default=1)),
                ('photo', models.ImageField(default='noimage.png', upload_to='teachers')),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_with_teacher', to='payroll.Position')),
                ('time_schedual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Schedual')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'teacher',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary_date', models.DateField()),
                ('Salary_release_date', models.DateField()),
                ('salary', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('other', models.IntegerField(default=0)),
                ('advance_detected', models.IntegerField(default=0)),
                ('details', models.CharField(default='No Message', max_length=255)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Cash', max_length=8)),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_salary', to='payroll.Teacher')),
            ],
            options={
                'get_latest_by': 'pk',
                'ordering': ['-id'],
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Current Date')),
                ('type', models.CharField(choices=[('h', 'Holiday'), ('l', 'Leave')], default='l', max_length=8)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_paid', models.BooleanField(default=1)),
                ('reasion', models.CharField(max_length=50)),
                ('leave_message', models.TextField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='payroll.Teacher')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.CharField(max_length=10)),
                ('time_out', models.CharField(max_length=10)),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Teacher')),
            ],
            options={
                'get_latest_by': 'pk',
                'ordering': ['-id'],
                'db_table': 'employeeattendance',
            },
        ),
        migrations.CreateModel(
            name='AdvanceSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('monthly_detection', models.IntegerField(default=0)),
                ('detail', models.TextField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advancesalary', to='payroll.Teacher')),
            ],
            options={
                'get_latest_by': 'pk',
                'ordering': ['-id'],
                'db_table': 'advancesalary',
            },
        ),
    ]
