# Generated by Django 2.2.10 on 2020-09-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.CharField(default='https://facebook.com/intelexcel', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin',
            field=models.CharField(default='https://linkedin.com/intel3xcel', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter',
            field=models.CharField(default='https://twitter.com/intelexcel', max_length=255),
        ),
    ]
