# Generated by Django 2.2.10 on 2020-09-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='eventdefault.jpg', upload_to='frontend_events')),
                ('heading', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='RegisterNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='heading (max-value: 100 charators)')),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'registernow',
            },
        ),
        migrations.CreateModel(
            name='SchoolSummery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(default='thumbnail.jpg', upload_to='frontend_schoolsummery')),
                ('youtube_link', models.TextField()),
                ('description', models.TextField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'schoolsummery',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('back_image', models.ImageField(default='defaultslider.jpg', upload_to='frontend_sliders')),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'slider',
            },
        ),
        migrations.CreateModel(
            name='StudentActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='frontend_activities')),
                ('description', models.TextField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'studentactivities',
            },
        ),
        migrations.CreateModel(
            name='RegisteredStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=21)),
                ('register_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitesetting.RegisterNow')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'registeredstudent',
            },
        ),
        migrations.CreateModel(
            name='ExtraCources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='courcesdefault.jpg', upload_to='frontend_cources')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Teacher')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'extracources',
            },
        ),
    ]
