# Generated by Django 2.2.10 on 2020-09-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='redirect_link',
            field=models.CharField(default='#', max_length=150),
        ),
    ]
