# Generated by Django 2.2.10 on 2020-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0003_auto_20200910_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_email', models.EmailField(default='info@intelexcel.com', max_length=254)),
                ('contact_number', models.CharField(default='03242806949', max_length=20)),
                ('logo', models.ImageField(default='intelexcel.png', upload_to='schooldata')),
                ('Short_descrption', models.TextField(default='This is a service provider based educational system. trying to fill all of empty spaces in education system. need your suggestion. for any query please contact info@intelexcel.com', verbose_name='SHort Description will display in footer')),
                ('full_address', models.TextField()),
                ('twitter', models.CharField(default='https://twitter.com/intelexcel', max_length=255)),
                ('linkedin', models.CharField(default='https://linkedin.com/intel3xcel', max_length=255)),
                ('facebook', models.CharField(default='https://facebook.com/intelexcel', max_length=255)),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'mainsetting',
                'ordering': ['-id'],
            },
        ),
    ]
