# Generated by Django 2.2.10 on 2020-09-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0006_registeredstudent_inserted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=70)),
                ('about_description', models.CharField(max_length=355)),
                ('about_background', models.ImageField(default='thumbnail.jpg', upload_to='frontend_schoolsummery')),
            ],
            options={
                'db_table': 'about',
                'ordering': ['-id'],
            },
        ),
    ]
