# Generated by Django 2.2.10 on 2020-09-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='inserted_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='about',
            name='module_holder',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
