# Generated by Django 2.2.10 on 2020-09-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0009_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20, verbose_name='heading (max-value: 20 charators)')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'noticeboard',
                'ordering': ['-id'],
            },
        ),
    ]
