# Generated by Django 2.2.10 on 2020-09-03 23:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('admission_registration', models.CharField(max_length=35)),
                ('name_of_student', models.CharField(max_length=35)),
                ('father_name', models.CharField(max_length=35)),
                ('father_cnic', models.CharField(max_length=35)),
                ('cast', models.CharField(default='no', max_length=35)),
                ('father_profession', models.CharField(max_length=35)),
                ('date_of_birth', models.DateField()),
                ('contact', models.CharField(max_length=35)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('recieve_admissin_fee_with_admission', models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='no', max_length=15)),
                ('monthly_tution_fee', models.IntegerField(default=0)),
                ('concession_fee', models.IntegerField(default=0)),
                ('annual_fund', models.IntegerField(default=0)),
                ('free_student', models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='no', max_length=3)),
                ('father_email_address', models.EmailField(blank=True, max_length=100)),
                ('Student_email_address', models.EmailField(blank=True, max_length=100)),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('photo', models.ImageField(default='noimage.png', upload_to='students')),
                ('status', models.IntegerField(default=1)),
                ('status_date', models.DateField(default='2020-09-03')),
                ('admission_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Classes')),
                ('admission_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Section')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'admission',
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exams_name', models.CharField(max_length=100, unique=True)),
                ('exam_type', models.CharField(choices=[('midterm', 'midterm'), ('final', 'final'), ('classtest', 'class test'), ('assignment', 'assignment')], max_length=20)),
                ('marks', models.IntegerField()),
                ('exam_detail_file', models.FileField(blank=True, default='nofile.pdf', upload_to='exams', verbose_name='Exam Or Assignment Detail File')),
                ('open_date', models.DateField()),
                ('due_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('current_month', models.CharField(default='2020-09', max_length=20)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Classes')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Subject')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='StudentsMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('current_month', models.CharField(default='2020-09', max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Exams')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Admission')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'studentsmarks',
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.FloatField()),
                ('attendance', models.FloatField()),
                ('class_test', models.FloatField()),
                ('assignment', models.FloatField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('current_month', models.CharField(default='2020-09', max_length=20)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Classes')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Section')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Admission')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Subject')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'studentmark',
            },
        ),
        migrations.CreateModel(
            name='MarkDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('class_test', models.IntegerField()),
                ('assignment', models.IntegerField()),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Classes')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Subject')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'markdistribution',
            },
        ),
        migrations.CreateModel(
            name='ExamEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('current_month', models.CharField(default='2020-09', max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Exams')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Subject')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'examemail',
            },
        ),
        migrations.CreateModel(
            name='CalculateResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('exam_type', models.CharField(max_length=50)),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('current_month', models.CharField(default='2020-09', max_length=20)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Classes')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ExamEmail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Admission')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Subject')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'calculateresults',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=35)),
                ('subjects', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('attendance_selection', models.CharField(choices=[('1', 'Present'), ('2', 'Absent'), ('3', 'Leave'), ('4', 'Late-In'), ('4', 'Off By School')], default='Present', max_length=20)),
                ('remarks', models.TextField(default='No', null=True)),
                ('module_holder', models.CharField(max_length=50)),
                ('inserted_date', models.DateField(auto_now=True)),
                ('current_month', models.CharField(default='09/2020', max_length=20)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Classes')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Section')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Admission')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'attendance',
            },
        ),
    ]
