# Generated by Django 2.2.10 on 2020-09-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='password',
            field=models.CharField(default='student123', max_length=35),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status_date',
            field=models.DateField(default='2020-09-06'),
        ),
    ]
