# Generated by Django 2.2.10 on 2020-09-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200906_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='password',
            field=models.CharField(default='student123', max_length=255),
        ),
    ]
