# Generated by Django 2.2.10 on 2020-09-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200906_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='status_date',
            field=models.DateField(default='2020-09-10'),
        ),
    ]
