# Generated by Django 2.2.10 on 2020-10-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200923_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateresults',
            name='clear_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status_date',
            field=models.DateField(default='2020-10-23'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='current_month',
            field=models.CharField(default='10/2020', max_length=20),
        ),
        migrations.AlterField(
            model_name='calculateresults',
            name='current_month',
            field=models.CharField(default='2020-10', max_length=20),
        ),
        migrations.AlterField(
            model_name='examemail',
            name='current_month',
            field=models.CharField(default='2020-10', max_length=20),
        ),
        migrations.AlterField(
            model_name='exams',
            name='current_month',
            field=models.CharField(default='2020-10', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='current_month',
            field=models.CharField(default='2020-10', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='current_month',
            field=models.CharField(default='2020-10', max_length=20),
        ),
    ]
