# Generated by Django 2.2.10 on 2020-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20201023_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='status_date',
            field=models.DateField(default='2020-10-24'),
        ),
    ]
